= Preface

== Purpose

This document describes the {product_name} Resource Model, a model of descriptive resource meta-data.

The intended audience includes implementers and health IT standards experts.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^].

== Status

== History

This specification was derived from the {openehr_base_resource}[openEHR Resource specification^].

This specification is in the {spec_status} state. The development version of this document can be found at {S2base_latest_resource}[{S2base_latest_resource}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {S2specifications_forum}[{product_name} Specifications forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

