= Preface

== Purpose

This document specifies the {product_name} Model Support types, including structured identifiers, used by other {product_name} specifications.

The intended audience includes implementers and health IT standards experts.

== Related Documents

Prerequisite documents for reading this document include:

* The {s2_rm_overview}[S2 Architecture Overview^].
* The {s2_base_foundation_types}[S2 Foundation Types^].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {s2_base_latest_model_support}[{s2_base_latest_model_support}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Prior Art

This specification was derived from the {openehr_base_types}[openEHR Base Types specification^]. It has been slightly modified as follows:

* class names are converted to 'mixed snake case';
* simplification of structured identifiers in the `identification` package.

== Feedback

Feedback may be provided on the {s2_specifications_forum}[{product_name} forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an {product_name} specification is determined by a formal test of that artifact against the relevant {product_name} Implementation Technology Specification(s) (ITSs), such as a JSON-schema or OpenAPI specification. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.
