= Preface

== Purpose

This document describes the architecture of the {product_name} Change Control Model, which contains patterns used by other specifications.

The intended audience includes implementers and health IT standards experts.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^];

Related documents include:

* The {openehr_rm_support}[openEHR Support Information Model^];
* The {s2_base_model_support}[{product_name} Base Types^].

== History

This specification was derived from the Change Control section of the {openehr_rm_common}#_change_control_package[openEHR RM Common IM specification^].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {s2_base_latest_change_control}[{s2_base_latest_change_control}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {s2_specifications_forum}[{product_name} specifications forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].
