= Versioning

== Version Lifecycle

Content in Original versions has a lifecycle state associated with it, defined by a state machine whose states form the values of the enumeration `Version_lifecycle_state`. The state machine is shown below. The lifecycle state of a version is recorded in `Original_version._lifecycle_state_` attribute.

[.text-center]
.`Original_version._lifecycle_state_` state machine
image::{uml_diagrams_uri}/BASE-version_lifecycle.svg[id=version_lifecycle, align="center"]

One basic rule that must be observed with the use of states is that any transition requires the commit of a _new version_, even if the content is otherwise unchanged. This also means that transitions through a number of successive states entails a number of commits, each recording one transition.

=== Incomplete Content

Usually content will be committed in the `complete` state. However, in some circumstances, e.g. because the author has run out of time or due to an emergency, it may be committed as `incomplete` meaning that it is either partial and/or unreviewed. In hospitals this is a common occurrence. Unfinished content items (EHR Compositions, Demographic Parties etc) cannot be saved locally on the client machine, as this represents a security risk (since a client-side app or database is easier to compromise than a secure server). They must therefore be persisted on the server, either in the actual EHR (or other appropriate repository), or in a 'holding area' which is recognised as not being part of the primary destination record, but is still within a secure repository. Either way, the author normally retrieves the item(s) and after further work or review, promotes them into the final destination (i.e. patient EHR etc), in the `complete` state. Alternatively, the author might decide to throw them away, achieved by logical deletion, in which case the final commit is in the `deleted` state.

One of the consequences of accepting content that is semantically incomplete (e.g. may contain only partial clinical notes or incomplete demographic details) into the target EHR or other location is that it might also be technically 'incomplete', i.e. it may be missing mandatory data fields with respect to its generating archetypes. If being committed in the `complete` state, such data would be treated as invalid by the repository and rejected by the API.

NOTE: In the `incomplete` state, a limited form of invalidity is allowed: mandatory attributes may be absent. Concretely, single-valued attributes may have null values and container attributes may be empty, even though they may have minimum existence and cardinality respectively of one. All other validity requirements must be satisfied. In other words, in an `incomplete` commit, data may be missing, but it may not be wrong.

At an implementation level, templated and archetyped data being committed in the `incomplete` state therefore respects the same template and archetype(s), but with all existence and cardinality lower limits set to zero.

Transitioning from `incomplete` to `complete` states requires any missing fields to be populated. However, even if the `incomplete` content was technically valid and no new content is added, the transition to `complete` will generate a new `Version` regardless.

Systems and/or applications are responsible for implementing checks to find 'old' Versions in the `incomplete` state, and bring them to the relevant user's notice, or automatically deleting them or progressing them to `complete` in a reasonable way.

=== Abandoned and Inactive States

A content item that is in the `incomplete` state may lose relevance before it is ever completed, e.g. due to its data subject no longer being under care. The version containing such an item may be transitioned to the `abandoned` state to represent this state of affairs. If circumstances change again and the abandoned item once more becomes relevant, it may be transitioned back to the `incomplete` state via the `retrieve` transition.

An Original version may also be marked as being in the `inactive` state. This allows content that is understood as informationally valid with respect to the real world activities it represents - regardless of completion status - to be marked as no longer valid for use. The exact meaning of 'valid' will depend on the content: it may be that the content is no longer relevant or useful with respect to its original purpose. An `inactive` item may be reactivated back to the `complete` state, or retrieved back to the `incomplete` state (see table below for examples of when).

An abandoned or inactive content item may be deleted at any time, if it is determined to be of no potential future use.

The transitions related to the `abandoned` and `inactive` states are as follows, using a 'care plan' as the versioned content.

[cols="1,1,1,4", options="header"]
|===
|Initial +
 State          |Transition     |Target +
                                 State          |Example

|`incomplete`   |`abandon`      |`abandoned`    |A new care plan (the version content) was made in rehabilitation centre, but patient transferred to hospital before care plan was completed. 
                                                 The draft care plan is abandoned.

|`abandoned`    |`retrieve`     |`incomplete`   |Patient returns to rehab and care is resumed; the abandoned draft care plan is therefore brought back into use.

|`abandoned`    |`delete`     |`deleted`   |Previously abandoned care plan determined to be of no further use, and deleted.

|`complete`     |`deactivate`   |`inactive`     |A care plan (the version content) is in active use. Subsequently, the patient is discharged and the care plan is no longer actively maintained.

|`inactive`     |`reactivate`   |`complete`     |Patient is readmitted after discharge and the care plan is reactivated.

|`inactive`     |`retrieve`     |`incomplete`   |An inactive care plan is used as the draft for a new care plan.

|`inactive`    |`delete`     |`deleted`   |Previously de-activated care plan determined to be of no further use, and deleted.

|===

The most common of these transitions is likely to be `deactivate`, i.e. marking of the content as inactive once its operational relevance ceases.

== Logical Deletion

Within the lifecycle described above, deletion of existing top-level content items (i.e. the entire data contents of a Version) is somewhat of a special case in {product_name} and in EHRs in general. Medico-legal and traceability requirements mean that information cannot be literally removed, since it must always be possible to revert back to a previous state of the record in which the deleted information is intact. Accordingly, information can only ever be logically deleted. This is achieved by the following procedure in the Version container in question:

* create a new Version in the normal way;
* delete its `_data_` (which will by default be a copy of the data of the previous Version);
* set the `_lifecycle_state_` value to the code for `deleted`;
* commit in the normal way.

Logical deletion can be used for various reasons, including patient direction to remove material, and in the situation where information about a different patient has been incorrectly committed to a record, and has to be removed.

== Version Identification

The version identification scheme described here is adapted from cite:[Hnìtynka2004]. `Version` objects are identified by a `_uid_` attribute of type `OBJECT_VERSION_ID`, which is a three-part String identifier consisting of the sub-parts extractable via the accessors `_object_id()_`, `_creating_system_id()_` and `_version_tree_id()_` (see the {openehr_model_support}#_identification_package[`model_support.identification` package] in the BASE component), in which the `__object_id()__` part is a copy of the `__uid__` of the owning `Versioned_object` version container.

The following figure illustrates the scheme. The `Versioned_object._uid_` value - here, `"1234"` - is used as the `_object_id()_` part of the `_uid_` of every contained `Version`. Accordingly, each of those versions will have a `_uid_` following the pattern `"1234:system_id:version_tree_id"`. The use of the `_version_tree_id_` and `_system_id_` parts of the identifier are explained in the sections below. The function `Version._owner_id()_` is provided to enable a caller to easily obtain the 'owning version container' identifier.

[.text-center]
.Version identification system
image::{diagrams_uri}/version_identification_system.svg[id=version_identification_system, align="center", width=80%]

The following figure provides an example of multiple `VERSIONs` within a `Versioned_object`, where one of the versions has been merged from another system. This highlights the identifiers; details of original and merged versions are described below.

[.text-center]
.Version identification Example
image::{diagrams_uri}/version_identification_example.svg[id=version_identification_example, align="center", width=80%]

=== Local Versioning

The `_version_tree_id_` attribute of `Version._uid_` identifies a version of an item with respect to other versions in the same tree. The requirements of the identifier are the same as for typical versioning systems in use in software configuration management, and are as follows:

* to encode the relationship between versions in the version id, that is to say, version identifiers are constructed such that given a series of identifiers, the relative positions in the tree can be determined;
* to allow for branches, so that variants of a particular node can be created; e.g. due to translation, or for training purposes.

A suitable scheme satisfying the above requirements for health information is the simplest possible, i.e. a single number representing the version. Version identifiers thus start at 1 and continue by single increments. The succession of version identifiers formed by changes over time is known as the "trunk" of the version tree.

To support branching, a further pair of numbers is added. The first number identifies the branch (e.g. the 1st branch, 2nd branch etc from that trunk node), while the second identifies the version. Both of these numbers also start at '1'. The result of this is that version numbers like '1.1.1' (first version of first branch from trunk node 1), '2.3.3' (3rd version of 3rd branch from trunk node 2) are possible. Inside {product_name} systems where sharing with other systems does not occur, it is expected that branched versioning will be used rarely; translation is likely to be the only reason (for example if a Portuguese translation of an English language version of a Composition is made).

=== Distributed Versioning

However, in a distributed environment where copying and subsequent modification can occur, there are more requirements of the version identification scheme, as follows:

* it must be possible for an item to be copied and for local modifications then to be made without causing version clashes;
* it must be possible to send more recent versions from the original system to a target system that has already received earlier versions, and for these versions to be distinguishable from versions in the receiving system, including the previously imported versions - this enables the receiving system to know how and where to commit the received versions;
* it must be guaranteed that any version of any object is uniquely identified globally, no matter whether it is a locally created trunk version, a locally created branch version or a version containing changes made to a copied version.

To satisfy these needs, two modifications are made to the identification scheme. The first is the addition of the `_creating_system_id_` attribute of `Version._uid_`, representing the system where the version was created. This is a machine processable identifier, such as a reverse internet address or GUID.

Whenever a new `Original_version` in a particular `Versioned_object` (with a particular Uid) is created locally, the `Version._uid.creating_system_id_` is set to the identifier of the local system; if the version was imported, `_creating_system_id_` will already have been set to the identifier of the system of original creation.

The second modification is to require branching version identifiers to be used when local modifications are made to versions copied from elsewhere; this ensures that the modifications now being made in the target system are considered in a global sense as logical branches or variants rather than trunk versions which are made in the originating system. It also allows later trunk versions from the originating system to be copied at some future time to the target system without version identifier clashes. In summary, the scheme uses the tuple {`_object_id_`, `_creating_system_id_`, `_version_tree_id_`} to globally uniquely identify any {product_name} `Version` object.

== Class Descriptions

include::{uml_export_dir}/classes/{pkg}versioned_object.adoc[]

include::{uml_export_dir}/classes/{pkg}version.adoc[]

include::{uml_export_dir}/classes/{pkg}original_version.adoc[]

include::{uml_export_dir}/classes/{pkg}imported_version.adoc[]

include::{uml_export_dir}/classes/{pkg}contribution.adoc[]

include::{uml_export_dir}/classes/{pkg}audit_details.adoc[]

include::{uml_export_dir}/classes/{pkg}attestation.adoc[]

include::{uml_export_dir}/classes/{pkg}audit_change_type.adoc[]

include::{uml_export_dir}/classes/{pkg}attestation_reason.adoc[]

include::{uml_export_dir}/classes/{pkg}version_lifecycle_state.adoc[]
