= Preface

== Purpose

This document describes the architecture of the {product_name} Change Control Model, which defines versioning of the S2 EHR.

The intended audience includes implementers and health IT standards experts.

== Related Documents

Prerequisite documents for reading this document include:

* The {s2_rm_overview}[S2 Architecture Overview^].

Related documents include:

* The {openehr_rm_common}#_change_control_package[openEHR Change Control package^];
* The {s2_base_model_support}[{product_name} Base Types^].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {s2_base_latest_change_control}[{s2_base_latest_change_control}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Prior Art

This specification was derived from the Change Control section of the {openehr_rm_common}#_change_control_package[openEHR RM Common IM specification^]. It has been slightly modified as follows:

* class names are converted to 'mixed snake case';
* the `Audit_details` class is slightly modified;
* `Version.lifecycle_state` is represented by an enumeration rather than a coded text.

There are no changes to the openEHR versioning semantics.

== Feedback

Feedback may be provided on the {s2_specifications_forum}[{product_name} specifications forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an {product_name} specification is determined by a formal test of that artifact against the relevant {product_name} Implementation Technology Specification(s) (ITSs), such as a JSON-schema or OpenAPI specification. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.