= Primitive Types

== Overview

This section describes primitive types assumed by all {product_name} models. These are types supported directly by most programing languages, and usually available via either a class interface and/or a built-in primitive type. The following table lists the primitive types assumed by {product_name}.

[cols="1,4", options="header"]
|===
|Type name +
 in {product_name} |Description

|`Byte`     |a type whose value is an 8-bit value.
|`Boolean`  |logical True/False values; usually physically represented as an 
             integer, but need not be.
|`Integer`  |Integers.
|`Decimal`     |Real numbers in any interoperable representation, including
             single-width IEEE floating point.
|`String`   |represents unicode-enabled strings.
|===

The figure below illustrates these types. Simple inheritance relationships are shown which facilitate the type descriptions below. Actual inheritance from or substitutability for an `Any` class is not assumed, and is shown only to indicate which operations are available on each type. Data-oriented implementation type systems such as XML-schema do not have such operations.

[.text-center]
.`base.foundation_types.primitive_types` Package
image::{uml_diagrams_uri}/BASE-foundation_types.primitive_types.svg[id=foundation_types_primitive_types, align="center"]

== Unicode

It is assumed in the {product_name} specifications that Unicode is supported by the type `String`. Unicode is needed for all Asian, Arabic and other script languages, for both data values (particularly plain text and coded text) and for many predefined string attributes of the classes in the {product_name} Reference Model. It encompasses all existing character sets. In {product_name}, UTF-8 encoding is universally assumed.

== String-based Primitive Identifiers

Various commonly-used identifiers are treated as being represented as Strings with particular syntaxes and operations. These include `Uri`, `Uuid` (aka Guid), `Iso_oid` and `Internet_id` (reverse internet domain). The use of String representation is indicated by these types having the `Value_type` stereotype and additionally having the tag 'native_type' set to `"String"`.

Practically, such types are realised by String data representation with setters and accessors of the specific types. In Java for example, the following would be used.

[source, java]
----
public class Uuid extends String {

    public Uuid getUid() {return new Uuid(uid);}

    public setUid (Uuid aUid) {uid = aUid.value;}
}
----

== Class Definitions

include::{uml_export_dir}/classes/{pkg}boolean.adoc[]

include::{uml_export_dir}/classes/{pkg}comparable.adoc[]

include::{uml_export_dir}/classes/{pkg}byte.adoc[]

include::{uml_export_dir}/classes/{pkg}string.adoc[]

include::{uml_export_dir}/classes/{pkg}numeric.adoc[]

include::{uml_export_dir}/classes/{pkg}integer.adoc[]

include::{uml_export_dir}/classes/{pkg}real.adoc[]

include::{uml_export_dir}/classes/{pkg}uri.adoc[]

include::{uml_export_dir}/classes/{pkg}iso_oid.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}uuid.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}internet_id.adoc[leveloffset=+1]
