= Identification Package

== Overview

The `base_types.identification` package describes a model of references and identifiers for information entities and is illustrated below.

[.text-center]
.base.base_types.identification Package
image::{uml_diagrams_uri}/BASE-base_types.identification.svg[id=base_identification_types, align="center"]

== Requirements

The types within this package are designed for identifying and referencing the following kinds of informational entities:

*  *knowledge artefacts*: such as terminologies and terms, archetypes, etc.;
*  *data instances*: including healthcare-related data, demographic data and so on.

The former category is understood as 'source' artifacts in the same sense as 'source code', and accordingly have human-comprehensible identifiers in the same way that programming source files do. Compiled or generated forms of these artifacts may also have machine identifiers.

The latter category is understood as technical instances of model entities, for which computational identifiers are required.

Identifiers for both categories of entity require support for versioning. For knowledge artifacts, versions are assumed to be represented by the 3-part {semver}[Semantic Versioning^] system.

For data artifacts, versions follow the general model used in distributed version control systems, such that instances of an original item that have been subsequently modified in different systems ('forking') can be distinguished and merged if necessary.

== Design Approach

A key design decision has been to choose a string representation for all identifiers, with sub-parts being made available by appropriate functions which perform simple parsing on the string. This ensures that the data representation of identifiers (e.g. in XML) is as small as possible, while not losing object-oriented typing.

== Primitive Identifiers

Three kinds of types are defined in this package. The abstract UID type and its subtypes correspond to permanent, computationally reliable, primitive identifiers. Such identifiers are regarded as 'primitive' because they are treated as having no further internal structure, in the sense that part of such an identifier is not in general meaningful. The three subtypes `UUID`, `ISO_OID` and `INTERNET_ID` all have these properties, and are commonly accepted ways of uniquely identifying entities in computer systems. In openEHR (and generally in health informatics) they are usually used as parts of other identifiers.

NOTE: UUIDs are also commonly known as GUIDs, which may be used as a synonym within implementations.

A consequence of the string representation approach used in these classes is that to set an attribute of type UID from a string value, as would be done when reading from a database, de-serialising from XML or another text form, a piece of code that inspects the string structure has to be used in order to decide which of the subtypes of `UID` it is. This is a safe thing to do, since all three subtypes have mutually exclusive string patterns, and can easily be distinguished.

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}primitive_id.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}iso_oid.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}uuid.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}internet_id.adoc[leveloffset=+1]


== Instance Identifiers

The `OBJECT_ID` type and its descendants define instance identifiers for use within openEHR systems.

=== Identifying Versions within openEHR Versioned Containers

The `OBJECT_VERSION_ID` defines the semantics of the scheme used in openEHR for identifying versions within a versioned container, and uses a three-part identifier, consisting of:

* `_object_id_`: the identifier of the version container, in the form of a UID, typically a UUID;
* `_creating_system_id_`: the identifier of the system in which this version was created, of type UID, typically a reverse domain identifier;
* `_version_tree_id_`: the location in the version tree, as a 1- or 3-part numeric identifier, where the latter variant expresses branching; this is modelled using the `VERSION_TREE_ID` type.

The following provides a typical example:

----
87284370-2D4B-4e3d-A3F3-F303D2F4F34B::uk.nhs.ehr1::2
----

Under this scheme, multiple versions in the same container all have the same value for `_object_id_`, whilst their location in the version tree is given by the combination of the version tree identifier and the identifier of the creating system.

The requirements on the `_creating_system_id_` part of the identifier are that it be unique per system, and that it be easy to obtain or generate. It is also helpful if it is a meaningful identifier. The two most practical candidates appear to be UUIDs (which are not meaningful, but are easy to generate) and reverse internet domain identifiers (these are easy to determine if the system has an internet address, and are meaningful and directly processable, however unconnected systems pose a problem). ISO OIDs might also be used. All of these identifier types are accommodated via the use of UID. A full explanation of the version identification scheme and its capabilities is given in the {graphite_base_change_control}#_change_control_package[openEHR `change_control` package].

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}object_id.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}object_version_id.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}version_tree_id.adoc[leveloffset=+1]

== Knowledge Artifact Identifiers

Knowledge artifact identifiers are defined under the `Artifact_id` hierarchy.

=== Character Set

TBD

=== Case

TBD

=== Archetype Identifiers

The `ARCHETYPE_ID` subtype defines a multi-axial identifier for openEHR archetypes and templates, meaning that each identifier instance denotes a single archetype within a multi-dimensional space. The space is can be thought of as 3-dimensional, or as a versioned 2-dimensional space, consisting of the following axes:

* reference model entity, i.e. target of archetype, defined as:
** name of model issuer;
** name of model (there may be more than one from the same issuer);
** name of concept in model, i.e. class name
* domain concept;
* version.

The three outer sections are delimited by '.' characters, while the parts of the first section are delimited by `-` characters. As with any multi-axial identifier, the underlying principle of an archetype identifier is that all parts of the identifier must be able to be considered immutable. This means that no variable characteristic of an archetype (e.g. accrediting authority, which might change due to later accreditation by another authority, or may be multiple) can be included in its identifier. The explicit inclusion of version as part of the identifier means that two 'versions' of an archetype are actually two distinct archetypes. (The rules for archetype versions, revisions and other variants are given in the {openehr_am_id}[openEHR Archetype Identification specification].)

Examples of archetype identifiers include:

* `openEHR-EHR-SECTION.physical_examination.v2`
* `openEHR-EHR-SECTION.physical_examination-prenatal.v1`
* `Hl7-RIM-Act.progress_note.v1`
* `openEHR-EHR-Observation.progress_note-naturopathy.v2`

The grammar of archetype identifiers is given below in <<Syntaxes>>.

=== Terminology Identifiers

The `TERMINOLOGY_ID` subtype defines a globally unique single string identifier for terminologies. Terminology identifier values may include a version, either as part of the name, and/or according to the syntax defined in section 4.3.12 below. Examples of terminology identifiers include:

* "SNOMED-CT"
* "ICD9(1999)"

Currently the best authoritative source for the name part of the identifier (i.e. the part excluding the optional version part in parentheses) is the {nlm_umls_list}[US National Library of Medicine UMLS identifiers for included terminologies].

The scheme defined by the `TERMINOLOGY_ID` class provides for the situation where major 'versions' of a terminology such as the World Health Organisation's 'ICD10' and 'ICD10AM' (AM = 'Australian modifications') can accommodate a finer grain of versioning or revisioning, e.g.:

* "ICD10AM(3rd_ed)"
* "ICD10AM(4th_ed)"

The version part of a terminology identifier is in theory only absolutely necessary for those terminologies which break the rule that the concept being identified with a code loses or changes its meaning over versions of the terminology. This should not be the case for modern terminologies and ontologies, particularly those designed since the publication of Cimino's 'desiderata' cite:[Cimino1997] of which the principle of 'concept permanence' is applicable here - "A concept's meaning cannot change and it cannot be deleted from the vocabulary". However, there may be older terminologies, or specialised terminologies which may not have obeyed these rules, but which are still used; version ids should always be used for these. At a practical level, versions may be included routinely in some systems to support the potential medico-legal need to prove that a) a given code was in fact defined in the terminology (it may not have existed in an earlier edition) and b) that the meaning assumed in the system
was indeed the one assigned to it in the particular version or edition.

=== Equivalence

Although there are anomalies in some published terminologies and between some versions or editions of the same terminology, two terminology identifiers that are the same, disregarding the version part, can usually be considered as semantic equivalents in the terminology world. However, depending on which source of strings have been chosen for the name part of the identifier, two different identifiers may also indicate the same terminology, e.g. "ICD10AM_2000" (NLM identifier used in UMLS) and "ICD10AM(2nd_ed)" refer to the same thing.

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}artifact_id.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}archetype_id.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}archetype_hrid.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}terminology_id.adoc[leveloffset=+1]

== References

All `OBJECT_IDs` are used as identifier attributes within the thing they identify, in the same way as a database primary key. To refer to an identified object from another object, an instance of the class `OBJECT_REF` is used, in the same way as a database foreign key. This class supports distributed referencing, and includes the object namespace (typically 1:1 with some service, such as "terminology") and type. The general principle of object references is to be able to refer to an object available in a particular namespace or service. Usually they are used to refer to objects in other services, such as a demographic entity from within an EHR, but they may be used to refer to local objects as well. The type may be the concrete type of the referred-to object (e.g. "GP") or any proper ancestor (e.g. `PARTY`).

TODO: keep type?

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}object_ref.adoc[leveloffset=+1]

include::{uml_export_dir}/classes/{pkg}locatable_ref.adoc[leveloffset=+1]

[[_syntaxes]]
== Syntaxes

TODO: synchronise the syntax below with model.

The identifiers defined above are defined in their string form by the following EBNF grammar rules.

[source, ebnf]
--------
(* ------------------------- UID, OID, UUID -------------------------- *)
uid     = iso_oid | uuid | internet_id ;
iso_oid = number, { '.', number } ;
uuid    = hex-number, '-', hex-number, '-', hex-number, '-', hex-number, '-', hex-number ;

(* --------------------------- INTERNET_ID --------------------------- *)
(* According to IETF http://tools.ietf.org/html/rfc1034[RFC 1034] and  *)
(* http://tools.ietf.org/html/rfc1035[RFC 1035], as clarified by       *)
(* http://tools.ietf.org/html/rfc2181[RFC 2181] (section 11),          *)
(* and relaxation of https://tools.ietf.org/html/rfc1123[RFC 1123]     *)
(* The syntax of a domain name follows the grammar below. Slightly     *)
(* reduced for the purpose here, plus allows underscores.              *)
internet_id      = subdomain ;
subdomain        = label | subdomain, '.', label ;
label            = alphanum | alphanum-ext-str, alphanum ;

(* -------------------- HIER_BASED_ID, UID_BASED_ID ------------------ *)
hier_object_id = uid_based_id ;
uid_based_id   = root, [ '::', extension ] ;
root           = uid ;
extension      = ? any string ? ; (* any string *)

(* ------------------------- OBJECT_VERSION_ID ----------------------- *)
object_version_id  = object_id, '::', creating_system_id, '::', version_tree_id ;
object_id          = uid ;
creating_system_id = uid ;

(* ------------------------- VERSION_TREE_ID ------------------------- *)
version_tree_id = trunk_version, [ '.', branch_number, '.', branch_version ] ;
trunk_version   = number ;
branch_number   = number ;
branch_version  = number ;

(* -------------------------- ARCHETYPE_ID --------------------------- *)
archetype_id        = qualified_rm_entity, '.', domain_concept, '.', version_id ;
qualified-rm-entity = rm_originator, '-', rm_name, '-', rm_entity ;
rm-originator       = alphanum-str ;     (* id of org originating the RM on which this archetype is based *)
rm-name             = alphanum-str ;                      (* id of the RM on which the archetype is based *)
rm-entity           = alphanum-str ;                                       (* ontological level in the RM *)
domain-concept      = concept-name, { '-', specialisation } ; 
concept-name        = alphanum-str ;
specialisation      = alphanum-str ;
version-id          = 'v', ( '0' | non-zero-digit, [ number ] ) ;            (* numeric version identifier *)

(* ------------------------- TERMINOLOGY_ID -------------------------- *)
terminology_id = name-str, [ '(', name-str, ')' ] ;

(* -------------------------- generic rules -------------------------- *)
alphanum     = letter | digit ;
name-str     = letter, { letter | digit | '_' | '-' | '/' | '+' } ;
alphanum-str = letter, { letter | digit | '_' } ;
alphanum-ext-str = letter, { letter | digit | '_' | '-' } ;
letter       = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G'
             | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N'
             | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U'
             | 'V' | 'W' | 'X' | 'Y' | 'Z' | 'a' | 'b'
             | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i'
             | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p'
             | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w'
             | 'x' | 'y' | 'z' ;

number         = digit, { digit } ;
hex-number     = hex-digit, { hex-digit } ;
digit          = '0' | non-zero-digit ;
non-zero-digit = '1' | '2' | '3' | '4' | '5' | '6' | '7'| '8' | '9' ;
hex-digit      = digit | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' ;
--------


== Real-world Entity Identifiers

== Real World Identifier References

=== Requirements

Real world entities (RWEs) such as people, car engines, invoices, and appointments may all be assigned identifiers. In general, while some real world identifiers (RWIs) are 1:1 with their referent entities, none can be guaranteed so. Therefore, from a strict computational point of view, RWIs are not treated as reliable identifiers, but as _attributes_ of their owning objects, in the same ways as names and addresses for example.

Examples of RWE identifiers that are intended to be unique within the space of the issuing authority or organisation include:

* driver's licence id
* social security number
* passport number
* prescription id

The defining logical characteristic of RWIs is that they continue to identify the entities in question, regardless of how the latter change in time; for example a social security number does not change when someone changes his or her hair colour or address. In general it should be the case that if two RWIs are equal, they refer to the same RWE.

=== Semantics

The model defined in the `Rwe_id_ref` class allows the recording of three things as part of identifying an item of interest:

* the identifier given to the item of interest (mandatory).
* the issuing authority of the kind of id used (e.g. it might be the federal department of health) (optional);
* the assigner of the id to the item being identified. This is usually the organisation which created the item being identified (optional);

In addition, a type of item being identified can also be recorded, such as 'driver's licence' or 'Medicare card'. All fields are text fields, rather than coded, as no definitive vocabularies are available. However, some useful sources of terms exists, such as https://www.hl7.org/fhir/v2/0203/index.html[HL7v2 Table 0203^] for the `type` field. If using the latter, it is recommended to use the 'description', not the code.

Only the `identifier` field is mandatory to allow for use cases in which the other fields cannot be populated. However it is strongly recommended to populate the `type` and `issuer` fields where possible. In many cases the `issuer` and `assigner` have the same value, however two fields allow for the situation in which a central issuer provides blocks of identifiers (typically on some kind of form or other paperwork) to other organisations who then assign them to individuals, as is often done with prescription identifiers.

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}rwe_id_ref.adoc[leveloffset=+1]
