= Timing

== Overview

The `timing` package contains classes that provide a structured model of representation of timing of events in the past or future, in two forms: as a list of occurrences, or a pattern. The latter supports common ways of stating times such as used in medication prescription. The timing package is shown below.

[.text-center]
.base_types.timing Package
image::{uml_diagrams_uri}/BASE-base_types.timing.svg[id=timing_package, align="center"]

== Requirements

One of the difficulties with time is expressing future times, since potential occurrences, durations, repetitions cannot be expressed in the same way as actual time. Complicating the problem is the fact that humans tend to use very customary (i.e. calendar-anchored) ways of specifying time, such as "every second Tuesday", or "the first Sunday of the month". In clinical medicine, future time is most commonly used to express when medications or other therapies are intended to take place. They are often anchored to the calendar, and can easily include repetitions.

As with other time types, there are both simple and complex cases to consider. One of the most common examples of time in the future is the timing for drug administrations, e.g. "once every four hours". This could be represented as a simple periodic specification, consisting of a start point in time, a period, and a number of repetitions. The specification for taking blood sugar levels during a glucose test could be represented as a simple aperiodic series, e.g. ".5hr, 1hr, 2hr". However, even common specifications for prescriptions e.g. "three times a day for seven days" start to become quite
complex, for example, because "three times a day" might not mean literally 8 hours apart.

Some of the factors to consider in timing specifications are:

* period of repetition
* duration of activity being specified
* possible alignment to the calendar, e.g. "every 5th of the month"
* possible alignment to real world events e.g. "after meals"
* fuzziness

Because time is inherently "messy" (months do not all have the same number of days, leap years change the number of days in some years etc.), and because the relationship we have with time can also be arbitrary (e.g. anchored to mealtimes etc), specifying linguistically obvious specifications formally is quite challenging.

== Semantics

TBD

== Class Descriptions

include::{uml_export_dir}/classes/{pkg}timing.adoc[]

include::{uml_export_dir}/classes/{pkg}occurrence.adoc[]

include::{uml_export_dir}/classes/{pkg}occurrence_pattern.adoc[]

include::{uml_export_dir}/classes/{pkg}periodic_occurrence_pattern.adoc[]

include::{uml_export_dir}/classes/{pkg}date_time_specifier.adoc[]

include::{uml_export_dir}/classes/{pkg}time_specifier.adoc[]

include::{uml_export_dir}/classes/{pkg}clock_time.adoc[]

include::{uml_export_dir}/classes/{pkg}customary_time.adoc[]

include::{uml_export_dir}/classes/{pkg}temporal_relation.adoc[]
