=== OBJECT_ID Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__OBJECT_ID (abstract)__*

h|*Description*
2+a|Ancestor class of identifiers of informational objects. Ids may be completely meaningless, in which case their only job is to refer to something, or may carry some information to do with the identified object.

Object ids are used inside an object to identify that object. To identify another object in another service, use an `OBJECT_REF`, or else use a UID for local objects identified by UID. If none of the subtypes is suitable, direct instances of this class may be used.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*value*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|The value of the id in the form defined below.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*root* (): `<<_uid_class,UID>>`
a|The identifier of the conceptual namespace in which the object exists, within the identification scheme. Returns the part to the left of the first '::' separator, if any, or else the whole string.

h|*1..1*
|*extension* (): `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Optional local identifier of the object within the context of the root identifier. Returns the part to the right of the first '::' separator if any, or else any empty String.

h|*1..1*
|*has_extension* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|True if not `_extension_.is_empty()`.

h|*Invariants*
2+a|__Has_extension_valid__: `extension.is_empty xor has_extension`
|===
