=== Info_item Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__Info_item (abstract)__*

h|*Description*
2+a|Descendants are root points in information structures that are semantically independent.

h|*Inherit*
2+|`<<_locatable_class,Locatable>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*code*: `<<_terminology_term_class,Terminology_term>>`
a|Normative code defining the ontological taxonomic entity that the information in the sub-tree starting at this node relates to, or 'is about'.

Examples: heart rate, creatinine in urine, date first recognized.This code may be pre-coordinated to include relevant meaning modifiers e.g. 'average heart rate', 'maximum heart rate' in such a way that only comparable information objects are marked with the same code.

NOTE: not to be separately constrained in archetypes; this rule needs to be implemented in archetype tools.

h|*0..1*
|*original_code*: `<<_terminology_term_class,Terminology_term>>`
a|Original code defining this data item, May be more pre-coordinated than the `code` field, particularly for lab analytes.

h|*0..1*
|*links*: `List<<<_link_class,Link>>>`
a|Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `Entry`, `SECTION` and so on). Links may be to structures in other compositions.
|===
