=== Multimedia Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Multimedia*

h|*Description*
2+a|A specialisation of `Dv_encapsulated` for audiovisual and bio-signal types. Includes further metadata relating to multimedia types which are not applicable to other subtypes of `Dv_encapsulated`.

h|*Inherit*
2+|`<<_encapsulated_class,Encapsulated>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*alternate_text*: `<<_string_class,String>>`
a|Text to display in lieu of multimedia display/replay.

h|*0..1*
|*data*: `List<<<_byte_class,Byte>>>`
a|The actual data found at `_uri_`, if supplied inline, base64 encoded.

h|*1..1*
|*media_type*: `<<_terminology_code_class,Terminology_code>>`
a|Data media type coded from openEHR code set  media types  (interface for the IANA MIME types code set).
Example: image/jpeg; text/json.

h|*0..1*
|*hash*: `String`
a|SHA-1 integrity checksum as a Base64 string.

h|*0..1*
|*thumbnail*: `<<_multimedia_class,Multimedia>>`
a|The thumbnail for this item, if one exists; mainly for graphics formats.

h|*1..1*
|*size*: `<<_integer_class,Integer>>`
a|Original size in bytes of unencoded encapsulated data. I.e. coding in base64, hexadecimal etc. do not change the value of this attribute.

h|*0..1*
|*media_attributes*: `<<_hash_class,Hash>><<<_string_class,String>>, <<_string_class,String>>>`
a|Key / value list of media attributes, e.g. image size, video duration etc.

TODO: try to standardize keys?
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*is_external* (): `<<_boolean_class,Boolean>>`
a|Computed from the value of the `_uri_` attribute: True if  the data is stored externally to the record, as indicated by `_uri_`. A copy may also be stored internally, in which case `_is_expanded_` is also true.

h|*1..1*
|*is_inline* (): `<<_boolean_class,Boolean>>`
a|Computed from the value of the data attribute. True if  the  data is stored  in  expanded  form, ie within the EHR itself.

h|*Invariants*
2+a|__Not_empty__: `is_inline or is_external`

h|
2+a|__Media_type_valid__: `media_type /= Void and then code_set (Code_set_id_media_types).has_code (media_type)`

h|
2+a|__Compression_algorithm_validity__: `compression_algorithm /= Void implies code_set (Code_set_id_compression_algorithms).has_code (compression_algorithm)`

h|
2+a|__Integrity_check_validity__: `integrity_check /= Void implies integrity_check_algorithm /= Void`

h|
2+a|__Integrity_check_algorithm_validity__: `integrity_check_algorithm /= Void implies code_set (Code_set_id_integrity_check_algorithms).has_code (integrity_check_algorithm)`

h|
2+a|__Size_valid__: `size >= 0`
|===
