=== Coded_ordinal Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Coded_ordinal*

h|*Description*
2+a|A data type that represents integral score values, e.g. pain, Apgar values, etc, where there is:

* implied ordering,
* no implication that the distance between each value is constant, and
* the total number of values is finite;
* Integer values normally used but Real values are accommodated.

Note that although the term 'ordinal' in mathematics means natural numbers only, here any integer is allowed, since negative and zero values are often used by medical professionals for values around a neutral point. Examples of sets of ordinal values:

*   -3, -2, -1, 0, 1, 2, 3  -- reflex response values
*    0, 1, 2                  -- Apgar values

This class is used for recording any clinical datum which is customarily recorded using symbolic values. Example: the results on a urinalysis strip, e.g. `{neg, trace, +, \++, \+++}` are used for leucocytes, protein, nitrites etc; for non-haemolysed blood `{neg, trace, moderate}`; for haemolysed blood `{small, moderate, large}`.

h|*Inherit*
2+|`<<_ordered_value_class,Ordered_value>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*concept*: `<<_coded_text_class,Coded_text>>`
a|Coded textual representation of this value in the enumeration, which may be strings made from  +  symbols, or other enumerations of terms such as  `mild`, `moderate`, `severe`, or even the same number series as the values, e.g. 1, 2, 3.

h|*1..1 +
(redefined)*
|*magnitude*: `<<_integer_class,Integer>>`
a|Rank within ordered enumeration of values.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*less_than* __alias__ "<" ( +
other: `<<_coded_ordinal_class,Coded_ordinal>>[1]` +
): `<<_boolean_class,Boolean>>`
a|True if this Ordinal value is less than `_other_`.
|===
