=== Link Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Link*

h|*Description*
2+a|The `Link` type defines a logical relationship between two items, such as two `Entrys` or an `Entry` and a `Composition`. Links can be used across compositions, and across EHRs. Multiple `Links` can be attached to the root object of any archetyped structure to give the effect of a 1->N link.

1:1 and 1:N relationships between archetyped content elements (e.g. `Entrys`) can be expressed by using one, or more than one, respectively, `Links`. Chains of links can be used to see problem threads or other logical groupings of items.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*meaning*: `<<_terminology_term_class,Terminology_term>>`
a|Used to describe the relationship, usually in clinical terms, such as  in response to  (the relationship between test results and an order),  follow-up to  and so on. Such relationships can represent any clinically meaningful connection between pieces of information.

TODO: check use of DV_xxx types here.

h|*1..1*
|*type*: `<<_terminology_term_class,Terminology_term>>`
a|Indicates a clinical or domain-level meaning for the kind of link, for example 'problem' or 'issue'. If type values are designed appropriately, they can be used by the requestor of EHR extracts to categorise links which must be followed and which can be broken when the extract is created.

h|*1..1*
|*target*: `<<_uri_class,Uri>>`
a|The logical target object in the link relation, as per the linguistic sense of the meaning attribute.
|===
