=== Translation_details Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Translation_details*

h|*Description*
2+a|Class providing details of a natural language translation.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*language*: `<<_terminology_code_class,Terminology_code>>`
a|Language of the translation, coded using ISO 639-1 (2 character) language codes.

h|*1..1*
|*author*: `<<_hash_class,Hash>><<<_string_class,String>>, <<_string_class,String>>>`
a|Primary translator name and other demographic details.

h|*0..1*
|*accreditation*: `<<_string_class,String>>`
a|Accreditation of primary translator or group, usually a national translator's registration or association membership id.

h|*0..1*
|*other_details*: `<<_hash_class,Hash>><<<_string_class,String>>, <<_string_class,String>>>`
a|Any other meta-data.

h|*0..1*
|*version_last_translated*: `<<_string_class,String>>`
a|Version of this resource last time it was translated into the language represented by this `TRANSLATION_DETAILS` object.

h|*0..1*
|*other_contributors*: `List<<<_string_class,String>>>`
a|Additional contributors to this translation, each listed in the preferred format of the relevant organisation for the artefacts in question. A typical default is `"name <email>"` if nothing else is specified.
|===
