=== Measured Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Measured<V>*

h|*Description*
2+a|Additional data that may be recorded for measured form of a quantified item, including with optional accuracy, normal range and other reference ranges.

h|*Inherit*
2+|`<<_ordered_datum_class,Ordered_datum>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*value_status*: `<<_comparison_operator_enumeration,Comparison_operator>>`
a|Optional status of magnitude with respect to real-world value:

* `"="`   : real value is equal to recorded value
* `"<"`   : real value is < recorded value
* `">"`   : real value is > recorded value
* `"\<="` : real value is \<= recorded value
* `">="` : real value is >= recorded value

If not present, assumed meaning is  `"="` .

h|*0..1*
|*accuracy*: `<<_quantity_class,Quantity>>`
a|Accuracy of measurement. May be recorded in absolute units, or '%' units.

h|*0..1*
|*reference_ranges*: `List<<<_reference_range_class,Reference_range>>>`
a|Optional tagged other reference ranges for this value in its particular measurement context.

h|*0..1*
|*intepretation*: `<<_coded_text_class,Coded_text>>`
a|Interpretation with respect to normal/reference range, e.g. normal, low, very low, high, very high.

h|*0..1*
|*interpretation_guide*: `<<_text_class,Text>>`
a|Interpretation guide, typically in the form of a list of reference ranges based on phenotype, age, pregnancy status and so on.

h|*1..1*
|*value*: `V`
a|
|===
