=== Quantity Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Quantity*

h|*Description*
2+a|Quantitified type representing  scientific  quantities, i.e. quantities expressed as a magnitude and units. Units are expressed in the UCUM syntax (http://unitsofmeasure.org/ucum.html[Unified Code for Units of Measure (UCUM)], by Gunther Schadow and Clement J. McDonald of The Regenstrief Institute)  (case-sensitive form) by default, or another system if `_units_system_` is set.

Can also be used for time durations, where it is more convenient to treat these as simply a number of seconds rather than days, months, years (in the latter case, `DV_DURATION` may be used).

TODO: do we want to have an original_units field.

h|*Inherit*
2+|`<<_quantified_class,Quantified>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*units*: `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_term_class[Terminology_term^]`
a|Quantity units, expressed as a code from either UCUM or the units system specified in `_unit_system_`, when set.

In either case, the value is the code or syntax - normally formed of standard ASCII - which is in principal not the same as the display string, although in simple cases such as 'm' (for meters) it will be.

Code system is a URI identifying a terminology containing units concepts from the  (https://www.hl7.org/fhir/terminologies-systems.html[HL7 FHIR terminologies list]).

`Terminology_term.text` field contains the displayable form of the unit, e.g. `'°C'`.

Example values from UCUM: "kg/m^2", “mm[Hg]", "ms-1", "km/h".

TODO: review; status of UCUM in GCM (Stan)

h|*1..1 +
(redefined)*
|*value*: `Real`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*add* __alias__ "+" ( +
other: `<<_quantity_class,Quantity>>[1]` +
): `<<_quantity_class,Quantity>>`
a|Sum of this `DV_QUANTITY` and `_other_`.

h|*1..1 +
(redefined)*
|*subtract* __alias__ "-" ( +
other: `<<_quantity_class,Quantity>>[1]` +
): `<<_quantity_class,Quantity>>`
a|Difference of this `DV_QUANTITY` and `_other_`.

h|*1..1 +
(redefined)*
|*multiply* __alias__ "&#42;" ( +
factor: `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^][1]` +
): `<<_quantity_class,Quantity>>`
a|Product of this `DV_QUANTITY` and `_factor_`.

h|*1..1 +
(effected)*
|*is_equal* ( +
other: `<<_quantity_class,Quantity>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_quantity_class,Quantity>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Arithmetic value comparison. Returns True if current object is less than `_other_`. This operator is effected and/or redefined in descendants to provide the appropriate ordering semantics for concrete types.

In conjunction with `=`, enables the definition of the related functions `_greater_than_()` etc.
|===
