=== Proportion Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Proportion*

h|*Description*
2+a|A proportion of Quantities, Used for recording

* medication formulations
* admixture proportions (e.g. 3mg / L), densities, rates
* rate of events per time
* ratios of count per volume, mass etc.

h|*Inherit*
2+|`<<_measurable_class,Measurable>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*numerator*: `<<_quantity_class,Quantity>>`
a|Numerator of proportion.

h|*1..1*
|*denominator*: `<<_quantity_class,Quantity>>`
a|Denominator of ratio.

h|*0..1*
|*measured*: `<<_measured_class,Measured>><<<_proportion_class,Proportion>>>`
a|Additional data elements for measured quantities, including precision, accuracy and reference ranges.

h|*1..1 +
(redefined)*
|*magnitude*: `<<_decimal_class,Decimal>>`
a|The magnitude of the quantity.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*is_equal* ( +
other: `<<_proportion_class,Proportion>>[1]` +
): `<<_boolean_class,Boolean>>`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.

h|*1..1*
|*less_than* __alias__ "<" ( +
other: `<<_proportion_class,Proportion>>[1]` +
): `<<_boolean_class,Boolean>>`
a|Arithmetic value comparison. Returns True if current object is less than `_other_`. This operator is effected and/or redefined in descendants to provide the appropriate ordering semantics for concrete types.

In conjunction with `=`, enables the definition of the related functions `_greater_than_()` etc.

h|*1..1*
|*add* __alias__ "+" ( +
other: `<<_proportion_class,Proportion>>[1]` +
): `<<_proportion_class,Proportion>>`
a|Sum of two strictly comparable proportions.

h|*1..1*
|*subtract* __alias__ "-" ( +
other: `<<_proportion_class,Proportion>>[1]` +
): `<<_proportion_class,Proportion>>`
a|Difference between two strictly comparable proportions.

h|*1..1*
|*multiply* __alias__ "&#42;" ( +
factor: `<<_real_class,Real>>[1]` +
): `<<_proportion_class,Proportion>>`
a|Product of this Proportion and `_factor_`.

h|*1..1*
|*effective_value* (): `<<_decimal_class,Decimal>>` +
 +
__Post_result__: `Result = numerator.effective_value() / denominator.effective_value()`
a|
|===
