=== Text Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__Text (abstract)__*

h|*Description*
2+a|A text item, which may contain any amount of legal characters arranged as e.g. words, sentences etc (i.e. one `Text` may be more than one word). Visual formatting and hyperlinks may be included via markdown.

If the `_formatting_` field is set, the `_value_` field is affected as follows:

* `_formatting_ = "plain"`: plain text, may contain newlines;
* `_formatting_ = "plain_no_newlines"`: plain text with no newlines;
* `_formatting_ = "markdown"`: text in markdown format; use of CommonMark strongly recommended.

A `Text` can be coded by adding mappings to it.

h|*Inherit*
2+|`<<_data_value_class,Data_value>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*text*: `<<_string_class,String>>`
a|Displayable rendition of the item, regardless of its underlying structure. For `DV_CODED_TEXT`, this is the rubric of the complete term as provided by the terminology service.

h|*0..1*
|*formatting*: `<<_text_format_types_enumeration,Text_format_types>>`
a|If set, contains one of the following values:

* `"plain"`: use for plain text, possibly containing newlines, but otherwise unformatted;
* `"plain_no_newlines"`: use for text containing no newlines or other formatting;
* `"markdown"`: use for markdown formatted text, strongly recommended in the format of the CommonMark specification.

If not set, `"plain_no_newlines"` is assumed.

h|*Invariants*
2+a|__Formatting_valid__: `formatting /= void implies not formatting.is_empty`
|===
