=== Semi_quantitative Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Semi_quantitative<V>*

h|*Description*
2+a|A measurement expressed as a range (often termed a 'bucket' or 'bin') from within a set of ranges into which observed values are determined to be. Sometimes known as a 'semi-quantified' data type.

h|*Inherit*
2+|`<<_measurable_class,Measurable>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*range*: `<<_text_class,Text>>`
a|The range in which the value being reported was determined to be, e.g. '50 ug/dL .. 200 ug/dL'.

h|*0..1*
|*range_computable*: `<<_proper_interval_class,Proper_interval>><<<_decimal_class,Decimal>>>`
a|Optional fully computable representation of the `range` field, enabling computational comparison with other Stratified and Quantity values.

h|*0..1*
|*stratification_definition*: `<<_text_class,Text>>`
a|Optional description, code or online resource for the definition of the overall stratification in which this result falls.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*effective_value* (): `<<_decimal_class,Decimal>>` +
 +
__Post_result__: `result = if value != null then value.effective_value() else range_value end`
a|
|===
