=== Proportion Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Proportion*

h|*Description*
2+a|Models a proportion of quantities, Used for recording concentration ratios, e.g. Na:K (unitary denominator), albumin:creatinine ratio, densities, rates.

h|*Inherit*
2+|`<<_quantified_class,Quantified>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*numerator*: `<<_quantity_class,Quantity>>`
a|TODO: possibly needs to be a Quantified?

h|*1..1*
|*denominator*: `<<_quantity_class,Quantity>>`
a|Denominator of ratio.

h|*1..1 +
(redefined)*
|*value*: `Real`
a|Computed value of numerator / denominator.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*is_equal* ( +
other: `<<_proportion_class,Proportion>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_proportion_class,Proportion>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Arithmetic value comparison. Returns True if current object is less than `_other_`. This operator is effected and/or redefined in descendants to provide the appropriate ordering semantics for concrete types.

In conjunction with `=`, enables the definition of the related functions `_greater_than_()` etc.

h|*1..1 +
(redefined)*
|*add* __alias__ "+" ( +
other: `<<_proportion_class,Proportion>>[1]` +
): `<<_proportion_class,Proportion>>`
a|Sum of two strictly comparable proportions.

h|*1..1 +
(redefined)*
|*subtract* __alias__ "-" ( +
other: `<<_proportion_class,Proportion>>[1]` +
): `<<_proportion_class,Proportion>>`
a|Difference between two strictly comparable proportions.

h|*1..1 +
(redefined)*
|*multiply* __alias__ "&#42;" ( +
factor: `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^][1]` +
): `<<_proportion_class,Proportion>>`
a|Product of this Proportion and `_factor_`.
|===
