=== Original_version Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Original_version<T>*

h|*Description*
2+a|A Version containing locally created content and optional attestations.

h|*Inherit*
2+|`<<_version_class,Version>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*uid*: `<<_object_id_class,Object_id>>`
a|Stored version of inheritance precursor.

h|*0..1*
|*preceding_version_uid*: `<<_object_id_class,Object_id>>`
a|Stored version of inheritance precursor.

h|*0..1*
|*other_input_version_uids*: `List<<<_object_id_class,Object_id>>>`
a|Identifiers of other versions whose content was merged into this version, if any.

h|*1..1*
|*lifecycle_state*: `<<_version_lifecycle_state_enumeration,Version_lifecycle_state>>`
a|Lifecycle state of the content item in this version; coded by openEHR vocabulary `version lifecycle state`.

h|*0..1*
|*attestations*: `List<<<_attestation_class,Attestation>>>`
a|Set of attestations relating to this version.

h|*0..1*
|*data*: `T`
a|Data content of this Version.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*is_merged* (): `<<_boolean_class,Boolean>>`
a|True if this Version was created from more than just the preceding (checked out) version.

h|*Invariants*
2+a|__Attestations_valid__: `attestations /= Void implies not attestations.is_empty`

h|
2+a|__Is_merged_validity__: `other_input_version_ids = Void xor is_merged`

h|
2+a|__Other_input_version_uids_valid__: `other_input_version_uids /= Void implies not other_input_version_uids.is_empty`
|===
