=== Ratio Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Ratio*

h|*Description*
2+a|Models a ratio of values, i.e. where the numerator and denominator are both pure numbers. The `_valid_proportion_kind_` property of the `RatioKind` class is used to control the type attribute to be one of a defined set.

Used for recording titers (e.g. 1:128), concentration ratios, e.g. Na:K (unitary denominator), albumin:creatinine ratio, and percentages, e.g. red cell distirbution width (RDW).

Misuse: Should not be used to represent things like blood pressure which are often written using a  '/' character, giving the misleading impression that the item is a ratio, when in fact it is a structured value. Similarly, visual acuity, often written as (e.g.) "6/24" in clinical notes is not a ratio but an ordinal (which includes non-numeric symbols like CF = count fingers etc). Should not be used for formulations.

h|*Inherit*
2+|`<<_quantified_class,Quantified>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*numerator*: `<<_quantity_class,Quantity>>`
a|TODO: possibly needs to be a Quantified?

h|*1..1*
|*denominator*: `<<_quantity_class,Quantity>>`
a|Denominator of ratio.

h|*1..1*
|*type*: `<<_ratio_kind_enumeration,Ratio_kind>>`
a|

h|*1..1 +
(redefined)*
|*value*: `Real`
a|Computed value of numerator / denominator.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*is_equal* ( +
other: `<<_ratio_class,Ratio>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_ratio_class,Ratio>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Arithmetic value comparison. Returns True if current object is less than `_other_`. This operator is effected and/or redefined in descendants to provide the appropriate ordering semantics for concrete types.

In conjunction with `=`, enables the definition of the related functions `_greater_than_()` etc.

h|*1..1 +
(redefined)*
|*add* __alias__ "+" ( +
other: `<<_ratio_class,Ratio>>[1]` +
): `<<_ratio_class,Ratio>>`
a|Sum of two strictly comparable proportions.

h|*1..1 +
(redefined)*
|*subtract* __alias__ "-" ( +
other: `<<_ratio_class,Ratio>>[1]` +
): `<<_ratio_class,Ratio>>`
a|Difference between two strictly comparable proportions.

h|*1..1 +
(redefined)*
|*multiply* __alias__ "&#42;" ( +
factor: `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^][1]` +
): `<<_ratio_class,Ratio>>`
a|Product of this Proportion and `_factor_`.
|===
