=== Measured Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Measured<V>*

h|*Description*
2+a|Additional data that may be recorded for measured form of a quantified item, including with optional accuracy, normal range and other reference ranges.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*value_status*: `<<_comparison_operator_enumeration,Comparison_operator>>`
a|Optional status of magnitude with respect to real-world value:

* `"="`   : real value is equal to recorded value
* `"<"`   : real value is < recorded value
* `">"`   : real value is > recorded value
* `"\<="` : real value is \<= recorded value
* `">="` : real value is >= recorded value

If not present, assumed meaning is  `"="` .

h|*0..1*
|*accuracy*: `link:/releases/BASE/{base_release}/foundation_types.html#_comparable_class[Comparable^]`
a|Accuracy of measurement. A value of zero means no accuracy recorded.

h|*0..1*
|*accuracy_is_percent*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|If `True`, indicates that when this object was created, `_accuracy_` was recorded as a percent value; if `False`, as an absolute quantity value.

h|*0..1*
|*reference_ranges*: `List<<<_reference_range_class,Reference_range>>>`
a|Optional tagged other reference ranges for this value in its particular measurement context.

h|*0..1*
|*intepretation*: `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_term_class[Terminology_term^]`
a|Interpretation with respect to normal/reference range, e.g. 'H', 'L' etc.

h|*0..1*
|*interpretation_guide*: `<<_text_class,Text>>`
a|Interpretation guide, typically in the form of a list of reference ranges based on phenotype, age, pregnancy status and so on.
|===
