=== Parsable Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Parsable*

h|*Description*
2+a|Encapsulated data expressed as a parsable String, such as HTML5, a programming language source file etc.

h|*Inherit*
2+|`<<_encapsulated_class,Encapsulated>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*formalism*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Name of the formalism, e.g.  GLIF 1.0 ,  Proforma  etc.

h|*1..1*
|*value*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|The string, which may validly be empty in some syntaxes.

h|*0..1*
|*encoding*: `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_code_class[Terminology_code^]`
a|Name of character encoding scheme in which this value is encoded. Coded from openEHR Code Set  character sets . Unicode is the default assumption in openEHR, with UTF-8 being the assumed encoding. This attribute allows for variations from these assumptions.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*size* (): `link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]`
a|Size in bytes of value.

h|*Invariants*
2+a|__Formalism_valid__: `not formalism.is_empty`

h|
2+a|__Size_valid__: `size >= 0`
|===
