=== Measured Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Measured<V>*

h|*Description*
2+a|Additional data that may be recorded for measured form of a quantified item, including with optional accuracy, normal range and other reference ranges.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*normal_range*: `<<_range_class,Range>>`
a|Optional normal range.

h|*0..1*
|*value_status*: `<<_comparison_operator_enumeration,Comparison_operator>>`
a|Optional status of magnitude with respect to real-world value:

* `"="`   : real value is equal to recorded value
* `"<"`   : real value is < recorded value
* `">"`   : real value is > recorded value
* `"\<="` : real value is \<= recorded value
* `">="` : real value is >= recorded value

If not present, assumed meaning is  `"="` .

h|*0..1*
|*precision*: `link:/releases/BASE/{base_release}/foundation_types.html#_integer_class[Integer^]`
a|Precision to which the value of the quantity is expressed, in terms of number of decimal places. The value 0 implies an integral quantity.
The value -1 implies no limit, i.e. any number of decimal places.

h|*0..1*
|*accuracy*: `link:/releases/BASE/{base_release}/foundation_types.html#_comparable_class[Comparable^]`
a|Accuracy of measurement. A value of zero means no accuracy recorded.

h|*0..1*
|*accuracy_is_percent*: `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|If `True`, indicates that when this object was created, `_accuracy_` was recorded as a percent value; if `False`, as an absolute quantity value.

h|*0..1*
|*other_reference_ranges*: `List<<<_reference_range_class,Reference_range>>>`
a|Optional tagged other reference ranges for this value in its particular measurement context.

h|*0..1*
|*intepretation*: `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_term_class[Terminology_term^]`
a|Interpretation with respect to normal range, e.g. 'H', 'L' etc.
|===
