=== Node Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__Node (abstract)__*

h|*Description*
2+a|Node carrying data about a real world Entity. May be represented as an atomic value, via the `_value_` field, or a further sub-structure, or both,

If the `_value_` property is set, it carries the normalized value. In cases where this is different in a significant way from the originally captured value, the `_original_value_` is used to capture the latter. Cases include: conversion of units; terminology conversion / mapping.

h|*Inherit*
2+|`<<_info_item_class,Info_item>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*null_flavor*: `<<_terminology_term_class,Terminology_term>>`
a|Flavor of null value, e.g. `253&#124;unknown&#124;`, `271&#124;no information&#124;`, `272&#124;masked&#124;`, and `273&#124;not applicable&#124;`.

TODO: correct to S2 codes

h|*0..1*
|*null_reason*: `<<_text_class,Text>>`
a|Optional specific reason for null value; if set, `_null_flavour_` must be set. Null reason may apply only to a minority of clinical data, commonly needed in reporting contexts.

h|*0..1*
|*items*: `List<<<_node_class,Node>>>`
a|Subordinate data items.

h|*0..1*
|*value*: `<<_data_value_class,Data_value>>`
a|_Normalized_ value within `Element`. Any concrete subtype of `Data_value` can be used.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*is_null* (): `<<_boolean_class,Boolean>>`
a|True if value logically not known, e.g. if indeterminate, not asked etc.

h|*Invariants*
2+a|__Inv_is_null_valid__: `is_null() = (value = Void)`

h|
2+a|__Inv_null_flavour_indicated__: `is_null() xor null_flavour = Void`

h|
2+a|__Inv_null_flavour_valid__: `is_null implies terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_null_flavour, null_flavour.defining_code)`

h|
2+a|__Inv_null_reason_valid__: `null_reason /= Void implies is_null()`
|===
