=== Quantity Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Quantity*

h|*Description*
2+a|Type representing physical quantities, i.e. quantities expressed as a value and units.

Units are expressed as a `Coded_term` to allow the original units string (from user application) to be recorded in `_units.value_`, and the coded form to be recorded in `_units.concept_`.

Can also be used for time durations, where it is more convenient to treat these as simply a number of seconds rather than days, months, years (in the latter case, `Duration_value` may be used).

h|*Inherit*
2+|`<<_quantified_class,Quantified>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*units*: `link:/releases/BASE/{base_release}/foundation_types.html#_coded_term_class[Coded_term^]`
a|Quantity units, expressed as a code from either UCUM or the units system specified in `_unit_system_`, when set.

In either case, the value is the code or syntax - normally formed of standard ASCII - which is in principal not the same as the display string, although in simple cases such as 'm' (for meters) it will be.

Code system is a URI identifying a terminology containing units concepts from the  (https://www.hl7.org/fhir/terminologies-systems.html[HL7 FHIR terminologies list]).

`Terminology_term.text` field contains the displayable form of the unit, e.g. `'°C'`.

Example values from UCUM: "kg/m^2", “mm[Hg]", "ms-1", "km/h".

TODO: review; status of UCUM in GCM (Stan)

h|*1..1 +
(redefined)*
|*value*: `Real`
a|

h|*0..1 +
(redefined)*
|*measured*: `<<_measured_class,Measured>><<<_quantity_class,Quantity>>>`
a|Additional data elements for measured quantities, including precision, accuracy and reference ranges.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*add* __alias__ "+" ( +
other: `<<_quantity_class,Quantity>>[1]` +
): `<<_quantity_class,Quantity>>`
a|Sum of this `DV_QUANTITY` and `_other_`.

h|*1..1 +
(redefined)*
|*subtract* __alias__ "-" ( +
other: `<<_quantity_class,Quantity>>[1]` +
): `<<_quantity_class,Quantity>>`
a|Difference of this `DV_QUANTITY` and `_other_`.

h|*1..1 +
(redefined)*
|*multiply* __alias__ "&#42;" ( +
factor: `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^][1]` +
): `<<_quantity_class,Quantity>>`
a|Product of this `DV_QUANTITY` and `_factor_`.

h|*1..1 +
(effected)*
|*is_equal* ( +
other: `<<_quantity_class,Quantity>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Value equality: return True if `this` and `_other_` are attached to objects considered to be equal in value.

.Parameters +
[horizontal]
`_other_`:: Other object for comparison.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_quantity_class,Quantity>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Arithmetic value comparison. Returns True if current object is less than `_other_`. This operator is effected and/or redefined in descendants to provide the appropriate ordering semantics for concrete types.

In conjunction with `=`, enables the definition of the related functions `_greater_than_()` etc.
|===
