=== Object_ref Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Object_ref*

h|*Description*
2+a|Class describing a reference to a `Locatable` instance whose identifier is `_id_`., which may exist locally or be maintained outside the current namespace, e.g. in another service. In a relational DB, equivalent to a 'foreign key' with extra meta-data.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*namespace*: `<<_string_class,String>>`
a|Namespace to which this identifier belongs in the local system context (and possibly in any other openEHR compliant environment) e.g. `"terminology"`, `"demographic"`. These names are not yet standardised. Legal values for `_namespace_` are:

* `"local"`
* `"unknown"`
* a string matching the standard regex `[a-zA-Z][a-zA-Z0-9_.:\/&?=+-]*`.

Note that the first two are just special values of the regex, and will be matched by it.

h|*1..1*
|*type*: `<<_string_class,String>>`
a|Name of the  class (concrete or abstract) of object to which this identifier type refers, e.g. `PARTY`, `PERSON`,  `GUIDELINE`  etc. These class names are from the relevant reference model. The type name `ANY` can be used to indicate that any type is accepted (e.g. if the type is unknown).

h|*1..1*
|*id*: `<<_object_id_class,Object_id>>`
a|Globally unique id of an object, regardless of where it is stored.

h|*0..1*
|*path*: `<<_string_class,String>>`
a|The path to an instance, as an absolute path with respect to the object found at `VERSION._data_`. An empty path means that the object referred to by `_id_` is being specified.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*as_uri* (): `<<_string_class,String>>`
a|A URI form of the reference, created by concatenating the following:

* scheme, e.g. `ehr:`, derived from `_namespace_`
* `_id.value_`
* `/` + `_path_`, where `_path_` is non-empty
|===
