=== Attestation Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Attestation*

h|*Description*
2+a|Record an attestation of a party (the committer) to item(s) of record content. An attestation is an explicit signing by one healthcare agent of particular content for various particular purposes, including:

* for authorisation of a controlled substance or procedure (e.g. sectioning of patient under mental health act);
* witnessing of content by senior clinical professional;
* indicating acknowledgement of content by intended recipient, e.g. GP who ordered a test result.

h|*Inherit*
2+|`<<_audit_details_class,Audit_details>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*attested_view*: `<<_multimedia_class,Multimedia>>`
a|Optional visual representation of content attested e.g. screen image.

TODO: fix data type.

h|*0..1*
|*proof*: `<<_string_class,String>>`
a|Proof of attestation.

h|*1..1*
|*is_pending*: `<<_boolean_class,Boolean>>`
a|True if this attestation is outstanding; False means it has been completed.

h|*1..1 +
(redefined)*
|*reason*: `<<_attestation_reason_enumeration,Attestation_reason>>`
a|Reason of this attestation. Optionally coded by the openEHR Terminology group  attestation reason ; includes values like  authorisation ,  witness  etc.

h|*Invariants*
2+a|__Items_valid__: `items /= Void implies not items.is_empty`

h|
2+a|__Reason_valid__: `(reason.generating_type.is_equal (“DV_CODED_TEXT”) implies terminology (Terminology_id_openehr).has_code_for_group_id (Group_id_attestation_reason, reason.defining_code))`
|===
