=== Participation Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Participation*

h|*Description*
2+a|Model of a participation of a Party (any Actor or Role) in an activity.  Used to represent any participation of a Party in some activity, which is not  explicitly in the model, e.g. assisting nurse. Can be used to record past or  future participations.

Should not be used in place of more permanent relationships between demographic entities.

GRAPHITE: equivalent of Attribution CEM

h|*Inherit*
2+|`<<_locatable_class,Locatable>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*function*: `<<_terminology_term_class,Terminology_term>>`
a|The function of the Party in this participation. Note that a given party might participate in more than one way in a particular activity.

h|*0..1*
|*role*: `<<_terminology_term_class,Terminology_term>>`
a|Role of participant within the organisation, e.g. cardiologist, senior nurse.

h|*1..1*
|*performer*: `<<_entity_ref_node_class,Entity_ref_node>>`
a|The id and possibly demographic system link of the party participating in the activity.

h|*0..1*
|*mode*: `<<_terminology_term_class,Terminology_term>>`
a|Optional field for recording the 'mode' of the performer / activity interaction, e.g. present, by telephone, by email etc.

h|*0..1*
|*time*: `<<_interval_class,Interval>><<<_date_time_class,Date_time>>>`
a|The time interval during which the participation took place, if it is used in an observational context (i.e. recording facts about the past); or the intended time interval of the participation when used in future contexts, such as EHR Instructions.
|===
