=== Rwe_id_ref Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Rwe_id_ref*

h|*Description*
2+a|Type for representing a reference to a real world entity, with an identifier, and other meta-data indicating the type of entity, issuer of the identifier and its assigner.

Misuse: `Rwe_id_ref` is not used to express identifiers generated by the infrastructure to refer to information items; the types `Object_id` and `Object_ref`and subtypes are defined for this purpose.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*issuer*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Optional authority which issues the kind of id used in the id field of this object.

h|*0..1*
|*assigner*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Optional organisation that assigned the id to the item being identified.

h|*1..1*
|*id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|The identifier value. Often structured, according to the definition of the issuing authority's rules.

h|*0..1*
|*type*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Optional identifier type, such as  prescription , or  Social Security Number . One day a controlled vocabulary might be possible for this.

h|*Invariants*
2+a|__Id_valid__: `not id.is_empty`
|===
