= Ordered Package: Quantities

== Overview

The `rm.base.data_types.ordered` package defines types used to represent number-based data types used in science and medicine. Temporal types (dates and times) are described in the next section.

== Requirements

=== Stated Versus Observed Values

A basic distinction for quantitative data is between the stated and the observed forms (or _a priori_ and _a posteriori_ forms). A stated quantity takes the form of a numeric value and any qualifying properties required to provide the complete semantics.

The observed form involves _measurement_, which is an attempt to determine the true value of some measurable real world phenomenon via the use of a method or device. Measurement involves a number of extra concepts, including:

* _accuracy_: the likely difference between the measured result and the true value;
* _reference range_: one or more value ranges relative to the specific subject of measurement, such as 'normal', 'high' and so on;
* _value status_: an indication of the relationship between the real value and the measurement that allows for limitations in device measurement, for example a device may display the value '< 20μg', indicating that the real weight is below its bottom measurement threshold. Typical possibilities include less-than and greater-than, as well as 'approximate', common with patient-reported observations.

Reference ranges are particularly useful with pathology test results, e.g. serum sodium, and vital signs.

=== Dimensioned Quantities

The most common kind of quantity is a dimensioned quantity, consisting of a real number and units. Examples of stated dimensioned quantities include:

* systolic BP: 110 mmHg
* weight: 78 kg

Examples of observed dimensioned quantities include:

* systolic BP: 140 mmHg
* systolic BP: 140 ±5 mmHg
* height: 178 cm
* rate of asthma attacks: 7 /week (approx)

=== Percentages

Percentages are commonly recorded in medicine, e.g. % red cell distribution width (RDW) which is the width of a distribution of RBC widths.

=== Ratios

A common quantitative type in science and medicine is the ratio, which consists of _two numbers_ and is used in situations like the following:

* Na:K concentration ratio (unitary denominator);
* albumin:creatinine ratio; TODO: check.

In general ratios have real number values, even if some consist only of integer values.

=== Titers

A titer is a specific type of observation that is used in two forms in healthcare:
* general chemistry: the concentration of a solute in a solvent as determined by titration;
* medicine: the concentration of an antibody, as determined by finding the highest dilution at which it is still able to cause agglutination of the antigen.

Titers are normally recorded in the textual form '1:128', and indicate only the concentration ratio, without including either units or types of substance involved. This differs from a 'proportion' below, in which proper dimensioned quantities are used.

=== Physical Proportions

A _proportion_ consists of _two physical quantities_, such as the proportion of two ingredients in a formulation of medication or the proportion of solid in a liquid e.g.:

* 250 mg / 500 ml (solute/solvent);
* 150 μg thyroxine in a 0.5g stable base.

=== Formulations

A _formulation_ consists of two or more substances mixed together, usually according to a particular procedure. A single solute/single solvent formulation may be considered a proportion, while more complex formulations would normally need to be represented by some higher-level structure, each leaf element of which contains the required kind of Quantity.

=== Ranges

Ranges are ubiquitous in science and medicine, and take both stated and observed forms. Examples include:

* healthy weight range, e.g. 48kg - 60kg
* normal range for urinalysis in pregnancy - protein, e.g. "nil" - "trace"

=== Reference Ranges

A reference range is a quantity range attached to a measured value, and is common for laboratory result values. The typical form of a reference range found in a pathology result indicates what is considered the 'normal' range for a measured value. Examples of reference ranges:

* normal range for serum Na is 135 - 145 mmol/l;
* desirable total cholesterol: < 5.5 mmol/l.

Ranges can also be quoted for drug administrations, in which case they are usually thought of as the 'therapeutic' range. For example, the anticonvulsant drug Carbamazepine has a therapeutic range of 20 - 40 &#956;Mol/l. In some cases, there are multiple ranges associated with a drug, for example, Salicylate has a therapeutic range of 1.0 - 2.5 mmol/l and a toxic range > 3.6 mmol/l

Various examples occur in which multiple ranges may be stated, including the following.

* The administration recommendations for drugs which depend on the particular patient state. For example, the therapeutic range of Cyclosporin (an immunosuppressant) is a function of time post-transplant for the affected organ, e.g. kidney: < 6 months: 250 - 350 &#956;g/l, > 6 months: 100 - 200 &#956;g/l;
* Normal ranges for blood IgG, IgA, IgM which vary significantly with the age in months from birth;
* Progesterone and pituitary hormones have ranges which are different for different phases of the menstrual cycle and for menopause. This may result in 4 or 5 ranges given for one result. Only one will apply to any particular patient - but the exact phase of the cycle may be unknown - so the ranges may need to be associated with the value with no 'normal' range.

=== Normal Status in Laboratory data

Most laboratories include a normal status with each result, which indicates where the value lies with respect to the normal range. Normal status comes in two forms:

* a logically Boolean 'abnormal' or 'normal' value;
* values indicating a relationship with a normal range, e.g. 'very low' | 'low' | 'normal' | 'high' | 'very high'.

=== Scores

Medicine is a domain in which symbols representing relative magnitudes are commonly used, without exact values being used. The main purpose is usually to classify patients into groups for which different decisions might be made. Such classifications are typically known as _scores_ or _scales_. For example the characterisation of pain as 'mild', 'medium', 'severe', or the reflex response to tendon percussion as pass:["-", "+/-", "+", "++", "+++", "++++"]. Many scores such as the Apgar Score, Glasgow Coma Scale (GCS), and Barthel Index are globally known and used.

In some cases, there may be no way (or need) to precisely quantify such values because they reflect a subjective experience of the patient or informal judgment by the clinician. However, they are understood as being ordered, e.g. pass:[`++`] is greater than pass:[`+`].

A second requirement for score and scale values is that in many cases there is a need to associate numeric values with the symbols, in order to facilitate ordered comparison, and also to enable longitudinal comparison across results of the same kind (e.g. pain, protein). The majority of scores and scales are limited to Integer values, but some use Real numbers interspersed with Integers e.g. the modified Borg CR 10 scale cite:[Hareendran_et_al_2012] for perceived exertion. In both cases, values may be negative, zero or positive.

=== Semi-quantitative Values

Certain quantities are represented by a process sometimes known as 'bucketing', rather than with point values. This involves stating which value range of a number of ranges an observable falls into. The effect is to convert real quantities into a relatively small number of named value ranges which are easier to understand and work with, such as the following for protein in urine:

* `"neg"`, `"trace"` (10 cells/&#956;l)
* `"small"` (<25 cells/&#956;l)
* `"moderate"` (<80 cells/&#956;l)
* `"large"` (>200 cells/&#956;l)

=== Countable Things

A common kind of data value in medicine is the dimensionless countable quantity, e.g.

* number of doses: 2;
* number of previous pregnancies: 1;
* number of tablets: 3.

Values of this type are always integral. Countable values need to be convertible to real numbers for statistical purposes, for example for a study of average number of pregnancies per couple.

Some countable entities such as tablets are divisible into major fractions, typically halves and occasionally quarters.

== Design

The `rm.base.data_types.ordered package` addresses the above requirements and is illustrated below.

[.text-center]
.rm.base.data_types.ordered package - quantities
image::{uml_diagrams_uri}/BASE-data_types.ordered-quantity.svg[id=base_data_types_quantity, align="center"]

=== Taxonomy

In order to make sense of the requirements in a systematic way, a taxonomy for quantified entities is used, illustrated below.

[.text-center]
.Ordered data types taxonomy
image::{uml_diagrams_uri}/BASE-data_types.ordered-taxonomy.svg[id=base_data_types_quantity_taxonomy, align="center"]

The root of the taxonomy is the class `Ordered_datum`.

The most basic differentiating characteristic of ordered values as described above is the distinction between stated (or 'pure') and observed form. The pure forms of ordered data types are defined under the abstract type `Ordered_value`. The observed form, kown here as  _measured_ form is represented by the type `Measured<V>`, whose generic parameter may be any `Ordered_value`. The type `Measured<V>` acts as a wrapper for any pure value, adding data specific to the act of measurement.

Beneath `Ordered_value` is a further differentiation into `Coded_ordinal` and further hierarchy under `Quantified`.

The `Coded_ordinal` type is used to represent data items whose values are fiat-assigned numerics, but imply no correlation with real world amounts or magnitudes. This type is used for scores as described in the requirements above. `Coded_ordinal` represents data values whose values are generally Integers, and which have symbolic or text names instead, such as `"mild"`, `"medium"`, `"severe"`. Each symbol can be assigned any Integer value, providing a basis for computable comparison. Typical uses for `Coded_ordinal` include representing values from the Apgar and Glasgow Coma Scales, e.g. `0｜heart rate absent｜`, `4｜withdraws from pain｜`. Although the numeric values of coded ordinal data items does not stricly measure anything, they are nevertheless commonly added to create final scores, which classify a patient condition or situation. No other mathematical operations have meaning for this type.

In contrast to `Coded_ordinal`, types under `Quantified` have numeric values that can meaningfully be added, subtracted, multiplied and divided. The hierarchy breaks out into
* `Temporal_value` - abstract parent of Date/time types;
* `Money` - representing amount of currency;
* `Measurable` - used to record values of true measurable continuous variables in the real world.

`Measurable` is further classified into `Simple_measurable` and `Compound_measurable`. The former represents 'atomic' measurable things, while the latter enables combinations to be formed to represent proportions, ratios and titers.

`Quantity` is used to represent amounts of measurable things, and has a real number magnitude, precision, and units. The `_units_` attribute contains the scientific unit represented as a `Coded_text`. This allows for representation of:
* the presentation form of the unit, e.g. `'°C'`';
* the meaning of the unit, e.g. 'degrees Centigrade';
* the code for the unit, which might come from SNOMED, UCUM or another appropriate terminology.

The type `Count` has an integer magnitude and is used to record naturally countable things such as number of pregnancies, number of steps taken by a physiotherapy patient and so on. There are no units in a `Count`. Countable quantities can be used to create instances of `Quantity`, such as during a statistical study which average tobacco consumption over a time period. Such a computation might cause the creation of `Quantity` objects representing values like {magnitude = 5.85, units = '/ week'}

A sibling type of `Simple_measurable` and `Compound_measurable` is defined, `Stratified<V>`, which is a generic type whose parameter may be a `Simple_measurable`. Stratified data items are used to represent so-called 'semi-quantitative' values reported in bands, a process sometimes known as 'binning' or 'bucketing'. This method is used frequently in reporting lab values (particularly urinalysis) in healthcare.

=== Measured Values

An important difference exists between values that are stated (e.g. as targets) and values that are measured in the real world. In the latter case, accuracy and precision are often recorded, and in clinical medicine, reference ranges relevant to the patient are often included as well.

The `Measured` class provides a place to record these extra data items, and may be instantiated in any instance of a descendant `Measurable` that represents a measurement.

The optional `_magnitude_status_` attribute can be used to provide a non-quantified indication of accuracy, and takes the following values:

* `"="` : magnitude is a point value
* `"<"` : value is < magnitude
* `">"` : value is > magnitude
* `"\<="` : value is \<= magnitude
* `">="` : value is >= magnitude
* `"~"` : value is approximately magnitude

If not present, the meaning is `"="`.

=== Ranges

Ranges are not considered an `Ordered_datum` in the taxonomy, but rather a related data type that consists of a range of `Ordered_datum` instances. Ranges are represented by the generic type `Range<T:Ordered_datum>` which enables a range of any of the other ordered type to be constructed.

== Class Descriptions

include::{uml_export_dir}/classes/{pkg}ordered_value.adoc[]

include::{uml_export_dir}/classes/{pkg}ordered_datum.adoc[]

include::{uml_export_dir}/classes/{pkg}coded_ordinal.adoc[]

include::{uml_export_dir}/classes/{pkg}quantified.adoc[]

include::{uml_export_dir}/classes/{pkg}money.adoc[]

include::{uml_export_dir}/classes/{pkg}measurable.adoc[]

include::{uml_export_dir}/classes/{pkg}simple_measurable.adoc[]

include::{uml_export_dir}/classes/{pkg}quantity.adoc[]

include::{uml_export_dir}/classes/{pkg}count.adoc[]

include::{uml_export_dir}/classes/{pkg}compound_measurable.adoc[]

include::{uml_export_dir}/classes/{pkg}proportion.adoc[]

include::{uml_export_dir}/classes/{pkg}ratio.adoc[]

include::{uml_export_dir}/classes/{pkg}ratio_kind.adoc[]

include::{uml_export_dir}/classes/{pkg}stratified.adoc[]

include::{uml_export_dir}/classes/{pkg}measured.adoc[]

include::{uml_export_dir}/classes/{pkg}reference_range.adoc[]

include::{uml_export_dir}/classes/{pkg}comparison_operator.adoc[]

include::{uml_export_dir}/classes/{pkg}range.adoc[]


