= Amendment Record

[cols="1,6,2,2", options="header"]
|===
|Issue|Details|Raiser, Implementer|Completed

4+^h|*BASE Release 0.8.5*

|[[latest_issue]]0.8.5
|{spec_tickets}/SBASE-52[SBASE-52^]. Change `Measured.interpretation` to `s2.QuantitativeInterpretationValues`; +
|J Coyle, +
N Davis, +
S Huff, +
T Beale
|[[latest_issue_date]]19 Oct 2023

4+^h|*BASE Release 0.7.5*

|0.7.5
|{spec_tickets}/SBASE-51[SBASE-51^]. Improve `Timing` type; +
{spec_tickets}/SBASE-33[SBASE-33^]. Specify terminology for built-in attributes in BASE classes; +
{spec_tickets}/SBASE-31[SBASE-31^]. Change `Coded_ordinal.magnitude` to `Integer`; +
{spec_tickets}/SBASE-8[SBASE-8^]. Define `null_flavour` codes to use in `Node`;`` +
{spec_tickets}/SBASE-14[SBASE-14^]. Define the meaning of `Ordered_value.precision`; +
{spec_tickets}/SBASE-15[SBASE-15^]. Represent normal status in quantitative lab result values; +
{spec_tickets}/SBASE-5[SBASE-5^]. Clarify meaning of `Terminology_code.terminology_id`; +
{spec_tickets}/SBASE-2[SBASE-2^]. Convert use of `Real` to `Decimal` types across RM.
|J Coyle, +
N Davis, +
S Huff, +
T Beale
|17 Nov 2023

|0.1.0
|Initial Writing: based on openEHR and HL7 FHIR Data types.
|T Beale
|10 Apr 2023

|===

