= Timing

== Overview

The `timing` package contains classes that provide a structured model of representation of timing of events in the past or future, in two forms: as a list of occurrences, and as a pattern. The latter supports common ways of stating times such as used in medication prescription. The timing package is shown below.

[.text-center]
.base_types.timing Package
image::{uml_diagrams_uri}/BASE-data_types.timing.svg[id=data_types_timing_package, align="center"]

== Requirements

The Timing model responds to the need for expressing the time(s) at which some event did occur in the past or should occur in the future. The past case is used for reporting occurrences of illness, pain or any other health-related matter, including mental health events. The future case is typically used to indicate when to perform some healthcare-related activity, such as medication administration or exercise.

In both cases there are two common ways to represent timing:

* *history*: a list of time-points, possibly with associated durations;
* *pattern*: in the form of a rule or simple algorithm that can be interpreted by humans to express the intended specific real-world times.

The latter may have a bounding time interval defined for it such as 'from tomorrow until end of the month' or 'until next week'.

Typical pattern examples include:

* twice a day for the last week;
* three times a day with meals for the next 7 days;
* once every four hours.

Some of the elements that need to be represented in timing specifications are:

* period of repetition;
* duration of activity being specified;
* possible alignment to the calendar, e.g. "every 5th of the month";
* possible alignment to real world events e.g. "after meals";
* variable precision.

== Semantics

TBD

== Class Descriptions

include::{uml_export_dir}/classes/{pkg}timing.adoc[]

include::{uml_export_dir}/classes/{pkg}occurrence.adoc[]

include::{uml_export_dir}/classes/{pkg}occurrence_pattern.adoc[]

include::{uml_export_dir}/classes/{pkg}time_specifier.adoc[]

include::{uml_export_dir}/classes/{pkg}period_specifier.adoc[]

include::{uml_export_dir}/classes/{pkg}day_specifier.adoc[]

include::{uml_export_dir}/classes/{pkg}hour_specifier.adoc[]

include::{uml_export_dir}/classes/{pkg}clock_time.adoc[]

include::{uml_export_dir}/classes/{pkg}customary_time.adoc[]

include::{uml_export_dir}/classes/{pkg}temporal_relation.adoc[]
