= Miscellaneous Types

== Boolean Values

The type `Boolean_value` is provided to represent true Boolean values, such as yes/no answers, true/false values and so on.

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}boolean_value.adoc[leveloffset=+1]

== Real World Identifier References

=== Requirements

Real world entities (RWEs) such as people, car engines, invoices, and appointments may all be assigned identifiers. In general, while some real world identifiers (RWIs) are 1:1 with their referent entities, none can be guaranteed so. Therefore, from a strict computational point of view, RWIs are not treated as reliable identifiers, but as _attributes_ of their owning objects, in the same ways as names and addresses for example.

Examples of RWE identifiers that are intended to be unique within the space of the issuing authority or organisation include:

* driver's licence id
* social security number
* passport number
* prescription id

The defining logical characteristic of RWIs is that they continue to identify the entities in question regardless of how the latter change in time; for example a social security number does not change when someone changes his or her address. In general it should be the case that if two RWIs are equal, they refer to the same RWE.

=== Semantics

The model defined in the `Rwe_id_ref` class allows the recording of three things as part of identifying an item of interest:

* the identifier given to the item of interest (mandatory).
* the issuing authority of the kind of id used (e.g. it might be the federal department of health) (optional);
* the assigner of the id to the item being identified. This is usually the organisation which created the item being identified (optional);

In addition, a type of item being identified can also be recorded, such as 'driver's licence' or 'Medicare card'. All fields are text fields, rather than coded, as no definitive vocabularies are available. However, some useful sources of terms exists, such as https://www.hl7.org/fhir/v2/0203/index.html[HL7v2 Table 0203^] for the `type` field. If using the latter, it is recommended to use the 'description', not the code.

Only the `identifier` field is mandatory to allow for use cases in which the other fields cannot be populated. However it is strongly recommended to populate the `type` and `issuer` fields where possible. In many cases the `issuer` and `assigner` have the same value, however two fields allow for the situation in which a central issuer provides blocks of identifiers (typically on some kind of form or other paperwork) to other organisations who then assign them to individuals, as is often done with prescription identifiers.

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}rwe_id_ref.adoc[leveloffset=+1]
