= Text Package

== Overview

The `base.data_types.text` package contains classes for representing textual data in the health record, including plain text with or without formatting and coded terms. It is illustrated below.

[.text-center]
.base.data_types.text package
image::{uml_diagrams_uri}/BASE-data_types.text.svg[id=base_data_types_text, align="center"]

== Requirements

=== Plain Text

Plain text items are used in clinical data in a number of cases, including:

* recording of narrative statements, e.g. visual observations, image interpretations;
* recording of patient responses, including quantities or dates not deemed sufficiently precise to be represented using structured quantitative or date/time date types;
* recording of values that would otherwise be coded, but for which no terminology is available.

Plain text items may contain formatting, and may also have mappings to one or more terminology codes for various purposes, including reimbursement and research.

=== Coded Text

==== Basic Requirements

Coded terms from controlled terminologies are used in the health record to enable machine processing of the data, via:

* _description_: to describe a state or event, e.g. state that an intestinal infection is _listeria monocytogenes_, or that the patient has supra-ventricular tachycardia;
* _classification_: to classify something into a specific category, e.g. to classify a specific procedure into a billing category;
* _translation_: codes may be rendered with a text value in a different language, if the terminology supports it i.e. if the requisite translation exists.

The first two categories may be broadly understood as 'names and values' of things. Values are normally drawn from _value-sets_, which are specific subsets of a terminology.

Classification is typically in the form of _additional_ code(s) to a descriptive code, leading to a requirement to support code _mappings_ for an initial code or text item. For example, a procedure may be coded locally as `snomed_ct::10761101000119105|Vacuum assisted vaginal delivery|`, but for billing purposes, with `ICD11::JB20|Single spontaneous delivery|`. The latter code would be added as a mapping of the former for the purpose of 'reimbursement'.

An overriding requirement for coded entities in the data are that they are independently intelligible, without resolution via a terminology service (which might not be available). Concretely this requires the term rubric (textual value) to be stored alongside the code.

==== Post-coordinated Terms

This specification assumes the possibility of _post-coordinated_ term expressions, which are constructed from primitive codes and an expression grammar. SNOMED CT for example {snomed_comp_grammar}[supports expressions^] such as `125605004 |fracture of bone| : 363698007 |finding site|  =  71341001 |bone structure of femur|`, which is a post-coordinated equivalent for `71620000|fracture of femur|`.

==== Preferred Terms

In cases where {product_name} data is used to represent data originally represented in other formats, one common requirement is to be able to represent both the term chosen by the user at data capture time, and also the corresponding _preferred term_, if the two are different. This allows both the user's specific choice and the standard text to be captured.

Secondly, where term mappings are represented it is useful to be able to capture not just the code or code-phrase of the mapped term, but the preferred term or expression text, in order to make the mapped term self-standing in the data.

=== Text Formatting

This specification assumes that the authors of narrative text content expect to be able to create longer tracts of text that may include paragraphs, bolding, bullet lists and other typical structures, as well as simple atoms of text containing bolding and so on.

It is assumed that the text associated with a coded term may include minimal formatting, i.e. a link and/or emphasis, but is devoid of other formatting or newlines.

== Design

=== Overview

All atomic text items are either instances of the type `Plain_text` or of `Coded_text`. Within archetyped structures, the parent type `Text` should be used wherever a coded or non-coded text item is allowed; `Coded_text` should be used wherever a text item must be coded, and `Plain_text` to force non-coded text. The `Text` type supports optional formatting and hyperlinking (see <<_formatting_and_hyperlinking>> below). The class `Coded_text` captures the association of two things:

* the code of a term known in the terminology service, recorded in the `_concept_` attribute of type `Terminology_code`;
* the text rubric of the term, recorded in the `_value_` attribute (inherited from `Text`).

The attribute `Terminology_code._code_string_` records a term code or post-coordinated code expression which may be used as an argument to a retrieval function in the terminology service to obtain the definition of the term or expression.

The model of `Coded_text` is designed to capture the _actual_ term chosen by the user or software at runtime, i.e. preferred term or synonym (for terminologies supporting synonyms), or a post-coordination of underlying distinct terms if an expression was chosen as the term (such as an expression supported by SNOMED CT). If the user makes any modification to the text value during data entry, a `Plain_text` object and associated mapping (see <<Mappings>>) must be used instead.

=== Negation

Negation is not supported as an additional Boolean property within a Coded text as in some models. It may be safely represented in one of the following ways:

* via a pre-coordinated term that includes negation, e.g `snomed_ct::409137002|No known drug allergy|`, if available;
* via a higher order structure such as a clinical statement on 'exclusions' that lists conditions or diagnoses that have been excluded (e.g. via testing).

=== Representation of Meaning-Modifying Terms

Meaning-modifying compound terms such as 'family history of breast cancer' and 'antibiotic prophylaxis recommended' may be represented in at least three ways as follows:

* via pre-coordinated terms, e.g. `snomed_ct::275937001|family history of cancer|`, if available;
* via a post-coordinated expression, e.g. `281666001 |family history of disorder| : 246090004 |associated finding| = 22298006 |myocardial infarction|`;
* via the use of separate terms within a larger structure, for example a clinical statement on 'family history' that lists key diagnoses (such as 'breast cancer') for specific family members.

The model described here may be used to implement all of these.

TODO: specific guidance, e.g. avoid complex post-coordination expressions?

=== Formatting and Hyperlinking

Formatting of the text in the `_value_` field of `Text`  instances is indicated via the optional `_formatting_` attribute. This may be used to control the use of newlines and general text formatting, for which mark-down is supported.

The `_formatting_` attribute may contain one of the following values, with the associated meaning.

* `Void`:  if no value is supplied, no formatting marks are assumed to exist in the text, other than newlines, and it may safely be passed in a 'straight-through' fashion to a display device with no further processing, if desired;
* `"markdown"`: the text is assumed to be markdown format, strongly recommended use of the {commonmark_spec}[CommonMark^] form of markdown, and should preferably be rendered via conversion to HTML in the usual way, but _may_ be passed straight through to display if unavoidable, since markdown is acceptably human-readable;
* `"plain"`: the text is treated as in the unformatted (`Void`) case above (newlines are allowed); this option is used to enable archetype-based modelling tools to clearly require a text object to be unformatted;
* `"plain_no_newlines"`: as for the plain case, but newlines are not allowed - the text is a simple 'atom'.

Not all CommonMark features are allowed in the `_value_` field, if it contains markdown. The following should not be used:

* HTML 'blocks';
* raw HTML;
* images - these may be included in {product_name} content via the `Multimedia` types.

==== Usage in Plain_text Instances

In a concrete instance of `Plain_text`, the following are the likely usages of the `_value_` and `_formatting_` attributes.

[cols="2,1,1", options="header"]
|===
|Requirement|`_value_` attribute|`_formatting_` attribute

|Plain text 'atom' +
 (no formatting, no newlines)
|plain text string
|`Void` or `"plain_no_newlines"`

|Plain text 'atom' with a hyperlink +
 (no formatting, no newlines)
|text string of form `[text](uri)` or other CommonMark link variant
|`"markdown"`

|Plain text paragraphs, +
 no other formatting
|plain text string with newlines
|`Void` or `"plain"`

|Formatted text with paragraphs, bolding, italics, bullet lists, links etc
|CommonMark text string
|`"markdown"`

|===

==== Usage in Coded_text Instances

In a concrete instance of `Coded_text`, the following are the likely usages of the `_value_` and `_formatting_` attributes.

[cols="2,1,1", options="header"]
|===
|Requirement|`_value_` attribute|`_formatting_` attribute

|Plain text of coded term
|plain text string
|`Void`

|Plain text of coded term with a hyperlink
|text string of form `[text](uri)` or other CommonMark link variant
|`"markdown"`

|Plain text of coded term or other text, containing newlines
|Plain formatted text
|Void or `"plain"`

|===

== Class Descriptions

include::{uml_export_dir}/classes/{pkg}text.adoc[]

include::{uml_export_dir}/classes/{pkg}plain_text.adoc[]

include::{uml_export_dir}/classes/{pkg}text_format_types.adoc[]

include::{uml_export_dir}/classes/{pkg}coded_text.adoc[]

