= Revision History

.[open]
[%collapsible]
====
[cols="1,6,2,2", options="header"]
|===
|Issue|Details|Resolution|Completed

4+^h|*BASE Release 0.9.0*

|[[latest_issue,0.9.0]]0.9.0
|{spec_tickets}/S2BASE-62[S2BASE-62^]. Add semi-quantitative data type; +
{spec_tickets}/S2BASE-63[S2BASE-63^]. Adjust Quantity hierarchy to separate compound and simple value types; +
{spec_tickets}/S2BASE-64[S2BASE-64^]. Improve days specification in Timing data type +
|J Coyle, +
N Davis, +
S Huff, +
T Beale
|[[latest_issue_date,10 Jan 2025]]10 Jan 2025

4+^h|*BASE Release 0.8.7*

4+^h|*BASE Release 0.8.6*

|0.8.6
|{spec_tickets}/S2BASE-59[S2BASE-59^]. Simplify `Object_ref` and `Object_id`. +
|D Perkins, +
T Beale
|27 Sep 2024

4+^h|*BASE Release 0.8.5*

|0.8.5
|{spec_tickets}/S2BASE-52[S2BASE-52^]. Change `Measured.interpretation` to `s2.QuantitativeInterpretationValues`; +
|J Coyle, +
N Davis, +
S Huff, +
T Beale
|27 Sep 2024

4+^h|*BASE Release 0.7.5*

|0.7.5
|{spec_tickets}/S2BASE-51[S2BASE-51^]. Improve `Timing` type; +
{spec_tickets}/S2BASE-33[S2BASE-33^]. Specify terminology for built-in attributes in BASE classes; +
{spec_tickets}/S2BASE-31[S2BASE-31^]. Change `Coded_ordinal.magnitude` to `Integer`; +
{spec_tickets}/S2BASE-8[S2BASE-8^]. Define `null_flavour` codes to use in `Node`;`` +
{spec_tickets}/S2BASE-14[S2BASE-14^]. Define the meaning of `Ordered_value.precision`; +
{spec_tickets}/S2BASE-15[S2BASE-15^]. Represent normal status in quantitative lab result values; +
{spec_tickets}/S2BASE-5[S2BASE-5^]. Clarify meaning of `Terminology_code.terminology_id`; +
{spec_tickets}/S2BASE-2[S2BASE-2^]. Convert use of `Real` to `Decimal` types across RM.
|J Coyle, +
N Davis, +
S Huff, +
T Beale
|17 Nov 2023

|0.1.0
|Initial Writing: based on openEHR and HL7 FHIR Data types.
|T Beale
|10 Apr 2023

|===

====